from pathlib import Path
import json,re,html
from bs4 import BeautifulSoup
HERE=Path(__file__).resolve().parent
P=HERE.parents[1]
def put(path,s):
 p=P/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s)
R=['/','/proiecte','/cum-functioneaza','/propune-un-proiect','/despre','/contact','/confidentialitate','/proiecte/fotbal-pentru-viitor']
E=['/en','/en/projects','/en/how-it-works','/en/propose-a-project','/en/about','/en/contact','/en/privacy','/en/projects/football-for-the-future']
labels=[['Acasă','Proiecte','Cum funcționează','Propune un proiect','Despre','Contact'],['Home','Projects','How it works','Propose a project','About','Contact']]
pdf='/Fotbal-pentru-Viitor-2026-10-03-corectat.pdf'; brief='/Fotbal-pentru-Viitor-Rezumat-2026-10-03-corectat.pdf'
project={'id':'fotbal-pentru-viitor','author':'George Dobritoiu','horizon':'2030–2040','domain':'sport','status':'proposal','pdf':pdf,'summaryPdf':brief,'ro':{'title':'Fotbal pentru Viitor','url':R[7],'description':'O propunere pentru copii activi, antrenori pregătiți și comunități care cresc prin fotbal.'},'en':{'title':'Football for the Future','url':E[7],'description':'A proposal for active children, trained coaches and communities that grow through football.'}}
project=json.loads((P/'data/proiecte.json').read_text())[0]
def image(name,alt,hero=False):
 return f'<img src="/assets/img/{name}-960.webp" srcset="/assets/img/{name}-480.webp 480w, /assets/img/{name}-960.webp 960w, /assets/img/{name}-1600.webp 1600w" sizes="(max-width: 760px) 100vw, 50vw" width="1600" height="{2400 if name=='city' else 1200}" alt="{alt}" '+('fetchpriority="high"' if hero else 'loading="lazy"')+' decoding="async">'
def button(url,text,secondary=False):return f'<a class="btn {"secondary" if secondary else ""}" href="{url}">{text} <span aria-hidden="true">↗</span></a>'
def header(en,i):
 paths=E if en else R; ll=labels[en]
 return '<a class="skip" href="#main">'+('Skip to content' if en else 'Mergi la conținut')+'</a><header class="site-header"><a class="site-brand" href="'+paths[0]+'">PROIECT<span>ROMÂNIA<span class="brand-dot">.</span></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">'+('Menu' if en else 'Meniu')+'</button><nav id="site-nav" class="site-nav" aria-label="'+('Main navigation' if en else 'Navigare principală')+'">'+''.join(f'<a href="{paths[n]}" '+('aria-current="page"' if i==n else '')+'>'+ll[n]+'</a>' for n in range(1,6))+'</nav><div class="languages"><a href="'+R[i]+'" lang="ro" '+('aria-current="page"' if not en else '')+'>RO</a><span>/</span><a href="'+E[i]+'" lang="en" '+('aria-current="page"' if en else '')+'>EN</a></div></header>'
def footer(en):
 paths=E if en else R
 return '<footer class="site-footer"><div><a class="site-brand" href="'+paths[0]+'">PROIECT<span>ROMÂNIA.</span></a><p>'+('Ideas with evidence. Projects with a plan.' if en else 'Idei argumentate. Proiecte cu un plan.')+'</p></div><div><a href="'+paths[3]+'">'+('Contribute a project' if en else 'Contribuie cu un proiect')+'</a><a href="'+paths[6]+'">'+('Privacy' if en else 'Confidențialitate')+'</a><a href="/CREDITS.md">'+('Image credits' if en else 'Credite foto')+'</a></div><p>'+('An initiative by George Dobritoiu.' if en else 'O inițiativă de George Dobritoiu.')+'</p></footer><div class="toast" id="toast" role="status" aria-live="polite"></div>'
def page(i,en,title,desc,content,football=False):
 path=(E if en else R)[i]; lang='en' if en else 'ro'; canonical='https://proiectromania.ro'+path
 schema={'@context':'https://schema.org','@type':'WebPage','name':title,'description':desc,'url':canonical,'inLanguage':lang,'isPartOf':{'@type':'WebSite','name':'Proiect România','url':'https://proiectromania.ro/'}}
 s=f'<!doctype html><html lang="{lang}"><head><script>document.documentElement.classList.add("js")</script><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | Proiect România</title><meta name="description" content="{html.escape(desc,quote=True)}"><link rel="canonical" href="{canonical}"><link rel="alternate" hreflang="ro" href="https://proiectromania.ro{R[i]}"><link rel="alternate" hreflang="en" href="https://proiectromania.ro{E[i]}"><link rel="alternate" hreflang="x-default" href="https://proiectromania.ro{R[i]}"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc,quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:type" content="website"><meta property="og:image" content="https://proiectromania.ro/assets/og.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/icon.svg">'+('<link rel="stylesheet" href="/assets/football.css">' if football else '')+'<link rel="stylesheet" href="/assets/site.css?rev=shared-design-1"><script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script></head><body class="'+('football-page' if football else 'platform-page')+'">'+header(en,i)+'<main id="main">'+content+'</main>'+footer(en)+'<script src="/assets/site.js" defer></script></body></html>'
 put('index.html' if path=='/' else path.strip('/')+'.html',s)
def intro(kicker,title,desc):return f'<section class="page-intro wrap"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{desc}</p></section>'
def block(title,body):return f'<section class="text-section"><h2>{title}</h2>{body}</section>'
def paragraphs(*ps):return ''.join('<p>'+p+'</p>' for p in ps)
def card(en):
 d=project['en' if en else 'ro'];return '<article class="project-card">'+image('football','Football pitch with grass and goals' if en else 'Teren de fotbal cu gazon și porți')+'<div class="project-card-body"><p class="eyebrow">'+('SPORT · PROPOSAL FOR DISCUSSION' if en else 'SPORT · PROPUNERE PENTRU DEZBATERE')+'</p><h3><a href="'+d['url']+'">'+d['title']+'</a></h3><p>'+d['description']+'</p><p class="meta">George Dobritoiu · 2030–2040</p>'+button(d['url'],'Explore the project' if en else 'Descoperă proiectul')+'</div></article>'
standards=[('Problema și dovezile','Descrie problema, cine este afectat și ce date o susțin. Include surse verificabile și data consultării.'),('Propunerea','Explică soluția, ce schimbă și cum se leagă de structurile existente.'),('Pilotul','Pornește la scară mică: loc, durată, beneficiari și condiții de extindere.'),('Bugetul estimat','Separă costurile, ipotezele, resursele disponibile și sursele de finanțare posibile de cele confirmate.'),('Indicatorii','Definește situația inițială, rezultatele urmărite și cum vor fi măsurate.'),('Riscurile','Prezintă riscurile, dependențele și măsurile de reducere a lor.'),('Responsabilii','Arată cine coordonează, cine execută și cine verifică rezultatele.'),('Conflictele de interese','Declară interesele profesionale, financiare și legăturile relevante ale autorului.')]
standards_en=[('Problem and evidence','Explain the problem, who is affected and the evidence behind it. Include verifiable sources and access dates.'),('Proposal','Describe the solution, what it changes and how it connects with existing structures.'),('Pilot','Start small: location, duration, participants and conditions for expansion.'),('Estimated budget','Separate costs, assumptions, available resources and potential funding from confirmed funding.'),('Indicators','Define the baseline, intended outcomes and how they will be measured.'),('Risks','Set out risks, dependencies and mitigation measures.'),('Responsibilities','Identify who coordinates, delivers and assesses results.'),('Conflicts of interest','Declare the author’s relevant professional, financial and organisational interests.')]
def form(en):
 return '<form class="join-form contact-form"><label>'+('Your name' if en else 'Numele tău')+'<input name="name" autocomplete="name" maxlength="100" required></label><label>'+('Area of contribution' if en else 'Domeniul contribuției')+'<input name="area" maxlength="150" required></label><label>'+('Your idea or contribution' if en else 'Ideea sau contribuția ta')+'<textarea name="message" rows="5" maxlength="3000" required></textarea></label><p class="small">'+('This opens WhatsApp with a draft. You review it and choose whether to send it. Avoid sensitive information or information about children.' if en else 'Se deschide WhatsApp cu un mesaj pregătit. Îl verifici și alegi dacă îl trimiți. Evită informațiile sensibile și datele despre copii.')+'</p><button class="btn" type="submit">'+('Prepare WhatsApp message' if en else 'Pregătește mesajul în WhatsApp')+' ↗</button><noscript><p>'+('Enable JavaScript to prepare the WhatsApp message.' if en else 'Activează JavaScript pentru a pregăti mesajul WhatsApp.')+'</p></noscript></form>'
for en in [False,True]:
 paths=E if en else R
 title='Romania is built through projects.' if en else 'România se construiește prin proiecte.'
 desc='An open platform for people who turn expertise into practical proposals for Romania.' if en else 'O platformă deschisă oamenilor care transformă experiența și ideile în propuneri concrete pentru România.'
 home='<section class="home-hero wrap"><div class="hero-text"><p class="eyebrow">'+('IDEAS. PEOPLE. PUBLIC GOOD.' if en else 'IDEI. OAMENI. BINE COMUN.')+'</p><h1>'+('Good ideas.<br>A <em>clear plan.</em><br>Real involvement.' if en else 'Idei bune.<br>Un <em>plan clar.</em><br>Oameni implicați.')+'</h1><p class="lead">'+desc+'</p><div class="actions">'+button(paths[1],'Explore projects' if en else 'Descoperă proiectele')+button(paths[3],'Propose a project' if en else 'Propune un proiect',True)+'</div></div><figure class="hero-photo">'+image('city','Calea Victoriei, Bucharest — public space and city life' if en else 'Calea Victoriei, București — spațiu public și viață urbană',True)+'<figcaption>'+('Bucharest · A place we share' if en else 'București · Un spațiu pe care îl împărțim')+'</figcaption></figure></section>'
 home+='<section class="band"><div class="wrap split"><p class="eyebrow">'+('WHY THIS PLATFORM' if en else 'DE CE ACEASTĂ PLATFORMĂ')+'</p><div><h2>'+title+'</h2><p>'+('We bring together proposals with evidence, budgets and implementation steps. Authors, practitioners and communities can contribute to a useful public conversation.' if en else 'Reunim propuneri cu dovezi, bugete și pași de implementare. Autori, profesioniști și comunități pot contribui la o conversație publică utilă.')+'</p><a class="text-link" href="'+paths[4]+'">'+('About the initiative →' if en else 'Despre inițiativă →')+'</a></div></div></section>'
 home+='<section class="wrap section-space"><div class="section-heading"><div><p class="eyebrow">'+('FROM IDEA TO PROPOSAL' if en else 'DE LA IDEE LA PROPUNERE')+'</p><h2>'+('Projects open for discussion' if en else 'Proiecte deschise dezbaterii')+'</h2></div><a class="text-link" href="'+paths[1]+'">'+('All projects →' if en else 'Toate proiectele →')+'</a></div>'+card(en)+'</section>'
 steps=[('Define','A real problem, supported by evidence.'),('Develop','A proposal, a budget and a small pilot.'),('Improve','Feedback from people who understand the field.')] if en else [('Definim','O problemă reală, susținută de dovezi.'),('Construim','O propunere, un buget și un pilot la scară mică.'),('Îmbunătățim','Feedback de la oameni care cunosc domeniul.')]
 home+='<section class="wrap section-space"><p class="eyebrow">'+('HOW WE WORK' if en else 'CUM LUCRĂM')+'</p><h2>'+('A useful idea deserves a clear method.' if en else 'O idee utilă merită o metodă clară.')+'</h2><div class="three-grid">'+''.join(f'<article class="step"><span class="step-number">0{n+1}</span><h3>{a}</h3><p>{b}</p></article>' for n,(a,b) in enumerate(steps))+'</div></section>'
 home+='<section class="join-band"><div class="wrap"><p class="eyebrow">'+('BUILD THE COMMUNITY' if en else 'CONSTRUIM COMUNITATEA')+'</p><h2>'+('Your experience can move a project forward.' if en else 'Experiența ta poate duce un proiect mai departe.')+'</h2><p>'+('We welcome authors, reviewers, researchers, designers and people who can help test proposals locally.' if en else 'Căutăm autori, evaluatori, cercetători, designeri și oameni care pot ajuta la testarea propunerilor în comunități.')+'</p>'+button(paths[5],'I want to contribute' if en else 'Vreau să contribui')+'<div class="author-calls"><p>'+('Seeking authors in: <strong>Education</strong>' if en else 'Căutăm autori pentru: <strong>Educație</strong>')+'</p><p>'+('Seeking authors in: <strong>Local development</strong>' if en else 'Căutăm autori pentru: <strong>Dezvoltare locală</strong>')+'</p></div></div></section>'
 page(0,en,'Practical ideas for Romania' if en else 'Idei concrete pentru România',desc,home)
 page(1,en,labels[en][1], 'Explore independent proposals and their implementation plans.' if en else 'Descoperă propuneri independente și planurile lor de implementare.',intro('PROJECT LIBRARY' if en else 'BIBLIOTECA DE PROIECTE','Proposals worth discussing.' if en else 'Propuneri care merită discutate.','Each project has an author, a clear problem and a plan. Publication invites discussion; it does not mean implementation or funding is secured.' if en else 'Fiecare proiect are un autor, o problemă clară și un plan. Publicarea invită la dezbatere; implementarea și finanțarea sunt etape distincte.')+'<section class="wrap section-space"><p class="meta">'+('1 project · Sport · Proposal for discussion' if en else '1 proiect · Sport · Propunere pentru dezbatere')+'</p>'+card(en)+'</section>')
 how=intro('METHOD' if en else 'METODĂ','From proposal to a tested project.' if en else 'De la propunere la un proiect testat.','A shared framework helps us compare ideas and learn from results.' if en else 'Un cadru comun ne ajută să comparăm idei și să învățăm din rezultate.')+'<div class="reading wrap">'
 how+=block('1. Submit a structured proposal' if en else '1. Trimite o propunere structurată',paragraphs('Use the minimum project standard: evidence, solution, pilot, resources and responsibilities.' if en else 'Folosește standardul minim al unui proiect: dovezi, soluție, pilot, resurse și responsabilități.'))
 how+=block('2. Review and improve' if en else '2. Analizăm și îmbunătățim',paragraphs('Proposals are assessed for public benefit, evidence, feasibility, clarity and conflicts of interest. Authors can be asked for clarifications.' if en else 'Propunerile sunt analizate după utilitatea publică, dovezi, fezabilitate, claritate și conflictele de interese. Autorilor li se pot cere clarificări.'))
 how+=block('3. Publish for discussion' if en else '3. Publicăm pentru dezbatere',paragraphs('Published proposals identify their author, assumptions, sources and status. Feedback informs revisions.' if en else 'Propunerile publicate identifică autorul, ipotezele, sursele și stadiul proiectului. Feedbackul contribuie la revizuiri.'))
 how+=block('4. Test before expanding' if en else '4. Testăm înainte de extindere',paragraphs('A pilot starts only when responsibilities, resources and safeguards are agreed. Results determine the next step.' if en else 'Un pilot începe când responsabilitățile, resursele și măsurile de protecție sunt stabilite. Rezultatele determină pasul următor.'))
 how+=block('Editorial policy — proposed for confirmation' if en else 'Politică editorială — propusă pentru confirmare',paragraphs('Acceptance or rejection will use the published criteria above, with reasons communicated to the author. Party campaigning and personal attacks are excluded. Authors may request withdrawal through the contact channel.' if en else 'Acceptarea sau respingerea va folosi criteriile publicate mai sus, cu motive comunicate autorului. Conținutul de partid și atacurile la persoane sunt excluse. Autorii pot cere retragerea prin canalul de contact.')+'<aside class="preview-only review-note" hidden>'+('To confirm before publication: who makes editorial decisions, the response time and the withdrawal procedure.' if en else 'De confirmat înainte de publicare: cine ia deciziile editoriale, termenul de răspuns și procedura de retragere.')+'</aside>')+'</div>'
 page(2,en,labels[en][2],'How proposals are submitted, reviewed and tested.' if en else 'Cum sunt propuse, analizate și testate proiectele.',how)
 propose=intro('CONTRIBUTE' if en else 'CONTRIBUIE','Bring expertise. Build a proposal.' if en else 'Adu experiența ta. Construiește o propunere.','You can submit a project or contribute to an existing one.' if en else 'Poți propune un proiect sau poți contribui la unul existent.')+'<div class="reading wrap"><h2>'+('Minimum project standard' if en else 'Standardul minim al unui proiect')+'</h2><ol class="standards">'+''.join('<li><h3>'+a+'</h3><p>'+b+'</p></li>' for a,b in (standards_en if en else standards))+'</ol><p>'+('Football for the Future provides a structural example. Its full document is available in Romanian.' if en else 'Documentul Fotbal pentru Viitor oferă un exemplu de structură pentru o propunere detaliată.')+'</p>'+button(pdf,'View the example (Romanian PDF)' if en else 'Vezi exemplul (PDF)',True)+block('Start a conversation' if en else 'Începe o conversație',paragraphs('Tell us the problem you want to address and how you can contribute. The first message can be short; the full project can follow.' if en else 'Spune-ne ce problemă vrei să abordezi și cum poți contribui. Primul mesaj poate fi scurt; proiectul complet poate urma.')+form(en))+'</div>'
 page(3,en,labels[en][3],'The minimum standard for a credible, practical project proposal.' if en else 'Standardul minim pentru o propunere de proiect argumentată și aplicabilă.',propose)
 about=intro('ABOUT THE PLATFORM' if en else 'DESPRE PLATFORMĂ','A place for constructive proposals.' if en else 'Un loc pentru propuneri constructive.','Proiect România is an initiative by George Dobritoiu, open to contributions from people with different areas of expertise.' if en else 'Proiect România este o inițiativă de George Dobritoiu, deschisă contribuțiilor oamenilor cu experiență în domenii diferite.')+'<div class="reading wrap">'+block('What brings us together' if en else 'Ce ne aduce împreună',paragraphs('We aim to make public discussion more useful through documented problems, clear proposals and implementation plans. Each project keeps its own identity and author.' if en else 'Ne propunem să facem dezbaterea publică mai utilă prin probleme documentate, propuneri clare și planuri de implementare. Fiecare proiect își păstrează identitatea și autorul.'))+block('Independence and integrity' if en else 'Independență și integritate',paragraphs('The author of a strategy and companies associated with them do not bid to implement that strategy. Relevant interests are declared with the proposal.' if en else 'Autorul unei strategii și firmele asociate lui nu licitează pentru implementarea ei. Interesele relevante sunt declarate împreună cu propunerea.','Dialogue with institutions is part of developing workable proposals. A proposal does not imply an institutional partnership or endorsement.' if en else 'Dialogul cu instituțiile face parte din dezvoltarea unor propuneri aplicabile. O propunere nu echivalează cu un parteneriat instituțional sau cu o susținere oficială.'))+'<aside class="preview-only review-note" hidden><h2>'+('How it started' if en else 'Cum a apărut')+'</h2><p>'+('George’s confirmed text will be added here. This placeholder appears only in Preview.' if en else 'Aici va fi adăugat textul confirmat de George. Acest placeholder apare doar în Preview.')+'</p></aside></div>'
 page(4,en,labels[en][4],'The purpose and integrity principles of Proiect România.' if en else 'Scopul și principiile de integritate ale Proiect România.',about)
 page(5,en,labels[en][5],'Contact the initiative to propose a project or contribute your expertise.' if en else 'Contactează inițiativa pentru a propune un proiect sau pentru a contribui cu experiența ta.',intro('LET’S TALK' if en else 'HAI SĂ VORBIM','What would you like to help build?' if en else 'La ce ai vrea să contribui?','Authors, reviewers, practitioners and community organisers are welcome.' if en else 'Sunt bineveniți autori, evaluatori, profesioniști și organizatori din comunități.')+'<div class="reading wrap">'+form(en)+'<p class="small">'+('The current contact channel is WhatsApp. A dedicated email and submission form will be added after activation.' if en else 'Canalul actual de contact este WhatsApp. O adresă dedicată de e-mail și un formular de trimitere vor fi adăugate după activare.')+'</p></div>')
 privacy=intro('PRIVACY' if en else 'CONFIDENȚIALITATE','About the data you share.' if en else 'Despre datele pe care le trimiți.','Draft information for review before the restructured site is published.' if en else 'Informații în lucru, pentru verificare înainte de publicarea site-ului restructurat.')+'<div class="reading wrap"><aside class="preview-only review-note" hidden>'+('Data controller: TO BE CONFIRMED by George — legal identity, address and privacy contact. Also confirm the legal basis, retention period and rights request process before publication.' if en else 'Operator de date: DE CONFIRMAT de George — identitatea legală, adresa și contactul pentru confidențialitate. De stabilit înainte de publicare: temeiul prelucrării, perioada de păstrare și procedura de exercitare a drepturilor.')+'</aside>'+block('The current contact form' if en else 'Formularul actual de contact',paragraphs('The page uses your entries to prepare a WhatsApp link in your browser. Opening WhatsApp does not send the message automatically. Sending it shares its content and your WhatsApp account details with the recipient, under WhatsApp’s terms.' if en else 'Pagina folosește câmpurile completate pentru a pregăti un link WhatsApp în browserul tău. Deschiderea WhatsApp nu trimite automat mesajul. Trimiterea comunică destinatarului conținutul și datele contului tău WhatsApp, conform condițiilor serviciului.','The form does not save entries to a website database. Hosting services can process technical access data. The final privacy notice must identify the responsible operator and applicable arrangements.' if en else 'Formularul nu salvează câmpurile într-o bază de date a site-ului. Serviciile de găzduire pot prelucra date tehnice de acces. Informarea finală trebuie să identifice operatorul responsabil și condițiile aplicabile.'))+'</div>'
 page(6,en,'Privacy' if en else 'Confidențialitate','Information about the current WhatsApp contact mechanism.' if en else 'Informații despre mecanismul actual de contact prin WhatsApp.',privacy)
 # Preserve every substantive football section and anchor; replace global chrome.
 source=Path(HERE/'source'/('football-for-the-future.html' if en else 'fotbal-pentru-viitor.html')).read_text()
 soup=BeautifulSoup(source,'html.parser');main=soup.main
 for a in main.find_all('a',href=True):
  h=a['href']
  if h.endswith('.pdf'): a['href']='/'+h.lstrip('/')
  elif h.startswith(('index.html','index-en.html')):a['href']=paths[5] if '#' in h else paths[0]
 for section in main.select('section.contact'):
  section.clear()
  section.append(BeautifulSoup('<h2>'+('Contribute to the project' if en else 'Contribuie la proiect')+'</h2>'+button(paths[5],'Get in touch' if en else 'Ia legătura cu noi'),'html.parser'))
 for a in main.select('a[href="#contact"]'):a['href']=paths[5]
 main.select_one('h1').clear();main.select_one('h1').append('Golden generations are developed.' if en else 'Generațiile de aur se formează.')
 hero=main.select_one('.hero-grid'); panel=main.select_one('.hero-panel')
 if panel:panel.decompose()
 hero.append(BeautifulSoup('<figure class="football-photo">'+image('football','Grass football pitch' if en else 'Teren de fotbal pe iarbă',True)+'<figcaption>'+('Illustrative photograph · MIROV / Unsplash' if en else 'Fotografie ilustrativă · MIROV / Unsplash')+'</figcaption></figure>','html.parser'))
 for node in main.select('.hero-copy'):
  node.string='We propose a system that develops competitive generations through investment in children, coaching and community infrastructure.' if en else 'Propunem un sistem care formează generații competitive prin investiții în copii, antrenori și infrastructura comunităților.'
 if en:
  notice=BeautifulSoup('<p class="translation-note">This page is an English translation of the project presentation. The full document and executive summary are available in Romanian.</p>','html.parser')
  main.select_one('.document-download').insert(0,notice)
 page(7,en,project['en' if en else 'ro']['title'],project['en' if en else 'ro']['description'],''.join(str(x) for x in main.contents),True)
put('assets/football.css',Path(HERE/'source'/'style.css').read_text())
# Keep old URLs as real HTTP redirects, including both extension variants.
redirects=[]
for old,new in [('fotbal-pentru-viitor',R[7]),('football-for-the-future',E[7]),('index-en',E[0]),('frf2030',R[7])]:
 for suffix in ['','.html']:redirects.append({'source':'/'+old+suffix,'destination':new,'statusCode':301})
put('vercel.json',json.dumps({'cleanUrls':True,'trailingSlash':False,'redirects':redirects,'headers':[{'source':'/assets/(.*)','headers':[{'key':'Cache-Control','value':'public, max-age=3600'}]}]},indent=2))
put('robots.txt','User-agent: *\nAllow: /\nSitemap: https://proiectromania.ro/sitemap.xml\n')
put('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://proiectromania.ro'+p+'</loc></url>' for p in R+E)+'</urlset>')
put('assets/icon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="8" fill="#172c38"/><path d="M11 30V10h10a7 7 0 0 1 0 14h-5v6zm5-11h5a2 2 0 0 0 0-4h-5z" fill="#f0c75e"/></svg>')
put('CREDITS.md','# Credite foto / Image credits\n\nPhotographs from Unsplash, cropped and compressed to WebP. Illustrative images; no affiliation or endorsement implied.\n\n- Calea Victoriei, Bucharest — Rebecca Hausner: https://unsplash.com/photos/a-city-street-lined-with-tall-buildings-and-trees-oLwMhGQ2QxY\n- Football pitch — MIROV: https://unsplash.com/photos/empty-soccer-goals-on-a-grassy-field-at-dawn-xdwgVR5WLp8\n\nLicense: https://unsplash.com/license\nDownloaded 3 October 2026.\n')
print('Generated',len(list(P.rglob('*.html'))),'pages')
