"""Bilingual editorial guide to existing chess education programmes."""
from pathlib import Path
from bs4 import BeautifulSoup
import json
import xml.etree.ElementTree as ET
P=Path(__file__).resolve().parents[2]
RO='/proiecte/sah-in-scoli'; EN='/en/projects/chess-in-schools'; BASE='https://proiectromania.ro'
BODIES={
'ro':'''<aside class="dem-note">Promovăm două inițiative existente, cu organizatorii lor. Această prezentare editorială nu anunță un parteneriat cu Proiect România.</aside>
<h2>Șahul are deja un loc în școlile din România</h2><p>Există programe de formare a profesorilor, cursuri, activități și opționale de șah. Existența lor nu înseamnă că șahul este materie obligatorie în toate școlile. Oferta și participarea se verifică la fiecare școală și la organizatori.</p>
<h2>1. Educație prin Șah</h2><p><strong>Organizator: Federația Română de Șah</strong>, în colaborare cu Ministerul Educației și Casa Corpului Didactic Ialomița, conform prezentării programului.</p><p>Programul pregătește cadre didactice din învățământul primar să folosească șahul ca instrument educațional. Pagina oficială descrie un curs online gratuit de 50 de ore: 20 de ore sincron și 30 de ore de studiu individual, cu 12 credite.</p><p>Organizatorii indică acreditarea prin OME nr. 6426 din 19.12.2022, pentru patru ani. Pentru seriile următoare, profesorii trebuie să confirme calendarul, eligibilitatea, locurile disponibile și situația acreditării direct la furnizor.</p><p><a class="btn" href="https://www.edusah.ro/info/">Program și participare ↗</a></p><p><a href="https://www.educatie-frsah.ro/?lang=ro">Platforma oficială de formare</a> · <a href="https://frsah.ro/">Federația Română de Șah</a></p>
<h2>2. Șah în Școală</h2><p><strong>Organizator: Clubul Sportiv Gambitul Damei Iași</strong>, împreună cu o rețea de profesori și coordonatori.</p><p>Programul urmărește introducerea sistematică a șahului în educația preuniversitară, ca activitate complementară. Include cursuri, formarea profesorilor, materiale, seturi de șah și evenimente pentru copii. Site-ul organizatorilor oferă acces la înscrierea școlilor și a profesorilor.</p><p>Organizatorul raportează activitate în 37 de județe. Datele despre amploare sunt declarații ale organizatorilor, nu o măsurare independentă realizată de Proiect România. Nu reproducem totalurile de beneficiari, care diferă între prezentările publice.</p><p><a class="btn" href="https://sahinscoala.org/programul/">Descoperă programul și înscrierile ↗</a></p>
<h2>Cum poți participa</h2><ul><li><strong>Profesor:</strong> consultă programele, verifică eligibilitatea pentru formare și discută cu conducerea școlii despre o activitate potrivită elevilor.</li><li><strong>Școală:</strong> desemnează un profesor de contact și cere organizatorilor condițiile actuale, resursele disponibile și pașii de înscriere.</li><li><strong>Părinte:</strong> întreabă școala dacă există un club sau un opțional de șah și transmite conducerii informațiile originale.</li><li><strong>Companie sau susținător:</strong> contactează organizatorii pentru nevoi concrete, precum materiale sau dotări. Clarifică în prealabil beneficiarii, costurile și modul de raportare.</li></ul><p>Formularele și înscrierile aparțin organizatorilor și se completează pe site-urile lor. Proiect România nu colectează înscrieri la aceste programe.</p>
<h2>Surse și actualizare</h2><ul><li><a href="https://www.edusah.ro/info/">Educație prin Șah — descrierea programului</a>.</li><li><a href="https://www.educatie-frsah.ro/?lang=ro">Platforma de formare a Federației Române de Șah</a>.</li><li><a href="https://sahinscoala.org/programul/">Șah în Școală — misiune, participare și date raportate</a>.</li><li><a href="https://www.galasocietatiicivile.ro/participants_project_2026.php?id=161&amp;section_id=8">Gala Societății Civile 2026 — prezentarea depusă de Clubul Sportiv Gambitul Damei Iași</a>.</li></ul><p class="meta">Surse consultate la 10 octombrie 2026. Calendarul, costurile eventualelor activități și condițiile de participare se confirmă direct la organizatori.</p>''',
'en':'''<aside class="dem-note">An editorial guide to two existing initiatives and their organisers. This listing does not announce a partnership with Proiect România.</aside>
<h2>Chess education is already taking place</h2><p>Teacher training, school activities and optional chess classes already exist in Romania. These initiatives do not mean chess is compulsory in every school. Availability depends on the school and programme.</p>
<h2>1. Educație prin Șah — Education through Chess</h2><p><strong>Romanian Chess Federation</strong>, working with the Ministry of Education and the Ialomița Teacher Training Centre, according to the programme description.</p><p>The programme trains primary-school teachers to use chess in education. Its official page describes free online training lasting 50 hours, with 20 live hours, 30 hours of individual study and 12 credits.</p><p>The provider cites a four-year accreditation under ministerial order 6426 of 19 December 2022. Confirm future course dates, eligibility, available places and accreditation status directly with the provider.</p><p><a class="btn" href="https://www.edusah.ro/info/">Programme and participation (RO) ↗</a></p><p><a href="https://www.educatie-frsah.ro/?lang=ro">Official training platform</a> · <a href="https://frsah.ro/">Romanian Chess Federation</a></p>
<h2>2. Șah în Școală — Chess in School</h2><p><strong>Clubul Sportiv Gambitul Damei Iași</strong>, supported by a network of teachers and coordinators.</p><p>The programme promotes structured chess activities in pre-university education, including classes, teacher training, materials, chess sets and children's events. Its website provides school and teacher registration routes.</p><p>The organiser reports activity in 37 counties. This is organiser-reported information, not an independent evaluation by Proiect România. We omit beneficiary totals because public descriptions give different figures.</p><p><a class="btn" href="https://sahinscoala.org/programul/">Explore the programme and registration (RO) ↗</a></p>
<h2>How to take part</h2><ul><li><strong>Teachers:</strong> check training eligibility and discuss suitable activities with school leaders.</li><li><strong>Schools:</strong> nominate a contact teacher and ask organisers about current requirements, resources and registration.</li><li><strong>Parents:</strong> ask about an existing chess club or optional class and share the original programme information.</li><li><strong>Businesses and supporters:</strong> discuss specific resource needs with organisers and agree beneficiaries, costs and reporting before supporting an activity.</li></ul><p>Registration takes place on the organisers’ websites. Proiect România does not collect applications for these programmes.</p>
<h2>Sources</h2><ul><li><a href="https://www.edusah.ro/info/">Educație prin Șah programme description</a> and <a href="https://www.educatie-frsah.ro/?lang=ro">training platform</a>.</li><li><a href="https://sahinscoala.org/programul/">Șah în Școală programme description</a>.</li><li><a href="https://www.galasocietatiicivile.ro/participants_project_2026.php?id=161&amp;section_id=8">Organiser's submission to Gala Societății Civile 2026</a>.</li></ul><p class="meta">Sources checked on 10 October 2026. Confirm current schedules, any activity fees and participation terms with the organisers.</p>'''}
for lang,path in [('ro',RO),('en',EN)]:
 en=lang=='en'; title='Chess in Romanian schools' if en else 'Șah în școlile din România'
 description='Two existing programmes: teacher training, school activities and ways to participate.' if en else 'Două programe existente: formarea profesorilor, activități în școli și modalități de participare.'
 template='en/projects/romanian-gcse.html' if en else 'proiecte/gcse-limba-romana.html'
 s=BeautifulSoup((P/template).read_text(),'html.parser');s.title.string=title+' | Proiect România'
 for sel,val in [('meta[name="description"]',description),('meta[property="og:title"]',title),('meta[property="og:description"]',description),('meta[property="og:url"]',BASE+path)]:s.select_one(sel)['content']=val
 s.select_one('link[rel="canonical"]')['href']=BASE+path
 for a in s.select('link[rel="alternate"]'):a['href']=BASE+(EN if a.get('hreflang')=='en' else RO)
 for a in s.select('.languages a'):a['href']=EN if a.get('lang')=='en' else RO
 for t in s.select('script[type="application/ld+json"]'):t.decompose()
 t=s.new_tag('script',type='application/ld+json');t.string=json.dumps({'@context':'https://schema.org','@type':'WebPage','name':title,'url':BASE+path,'inLanguage':lang},ensure_ascii=False);s.head.append(t)
 main=s.select_one('main');main.clear();main.append(BeautifulSoup(f'<article class="wrap dem-article"><a href="{"/en/projects#educatie" if en else "/proiecte#educatie"}">← {"Education projects" if en else "Proiecte de educație"}</a><p class="eyebrow">{"EDUCATION · EXISTING INITIATIVES" if en else "EDUCAȚIE · INIȚIATIVE EXISTENTE"}</p><h1>{title}</h1><p class="lead">{description}</p><div class="dem-body">{BODIES[lang]}</div></article>','html.parser'))
 (P/(path.lstrip('/')+'.html')).write_text(str(s))
v=json.loads((P/'vercel.json').read_text())
for path in [RO,EN]:
 if not any(x['source']==path for x in v['rewrites']):v['rewrites'].append({'source':path,'destination':path+'.html'})
 if not any(x['source']==path+'.html' for x in v['redirects']):v['redirects'].append({'source':path+'.html','destination':path,'statusCode':301})
(P/'vercel.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
ns='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',ns);tree=ET.parse(P/'sitemap.xml');root=tree.getroot()
known={x.text for x in root.findall('{'+ns+'}url/{'+ns+'}loc')}
for path in [RO,EN]:
 if BASE+path not in known:
  x=ET.SubElement(root,'{'+ns+'}url');ET.SubElement(x,'{'+ns+'}loc').text=BASE+path;ET.SubElement(x,'{'+ns+'}lastmod').text='2026-10-10'
tree.write(P/'sitemap.xml',encoding='utf-8',xml_declaration=True)
