"""Editorial homepage; rendered by navigation.py after the content generators."""
def render_home(en, items, card, cats):
    def t(ro, english): return english if en else ro
    directory = '/en/projects' if en else '/proiecte'
    propose = '/en/propose-a-project' if en else '/propune-un-proiect'
    about = '/en/about' if en else '/despre'
    how = '/en/how-it-works' if en else '/cum-functioneaza'
    contact = '/en/contact' if en else '/contact'
    football = '/en/projects/football-for-the-future' if en else '/proiecte/fotbal-pentru-viitor'
    featured_paths = ['/proiecte/hopefriday', '/proiecte/gcse-limba-romana', '/proiecte/partidul-ca-organizatie-responsabila', '/proiecte/cum-infiintezi-o-asociatie', '/proiecte/sah-in-scoli', '/proiecte/code-kids', '/proiecte/harta-reciclarii', '/proiecte/fertilizare-in-vitro']
    by_path = {item[0]: item for item in items}
    featured = ''.join(card(by_path[path], en, True) for path in featured_paths)
    categories = ''.join(f'<a href="{directory}#{key}"><span>{label[en]}</span><span aria-hidden="true">↗</span></a>' for key,label in cats.items())
    steps = [(t('O problemă reală','A real problem'), t('Pornim de la experiența oamenilor și de la dovezi verificabile.','We start with lived experience and evidence that can be checked.')),
             (t('Un plan clar','A clear plan'), t('Punem pe hârtie soluția, resursele, responsabilitățile și rezultatele urmărite.','We set out the solution, resources, responsibilities and intended results.')),
             (t('Un pas în comunitate','A step into the community'), t('Îmbunătățim propunerea prin feedback și pregătim condițiile unui pilot.','We improve the proposal through feedback and prepare the conditions for a pilot.'))]
    steps_html = ''.join(f'<li><span class="home-step-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></li>' for i,(title,body) in enumerate(steps))
    return f'''
<section class="wrap editorial-hero" aria-labelledby="home-title">
 <div class="editorial-copy"><p class="eyebrow">{t('O PLATFORMĂ DESCHISĂ IDEILOR CONSTRUCTIVE','AN OPEN PLATFORM FOR CONSTRUCTIVE IDEAS')}</p>
 <h1 id="home-title">{t('România se construiește.<br><em>Proiect cu proiect.</em>','Building Romania.<br><em>Project by project.</em>')}</h1>
 <p class="lead">{t('Punem împreună idei, experiență și oameni care vor să schimbe ceva. Le dăm o formă concretă: propuneri argumentate, ghiduri practice și planuri pentru comunități.','We bring together ideas, experience and people who want to make a difference. We turn them into evidence-based proposals, practical guides and plans for communities.')}</p>
 <div class="actions"><a class="btn" href="#proiecte-selectate">{t('Descoperă proiectele','Explore the projects')} <span aria-hidden="true">↓</span></a><a class="home-text-link" href="{propose}">{t('Propune o idee','Propose an idea')} <span aria-hidden="true">↗</span></a></div>
 <p class="home-origin">{t('O inițiativă de George Dobritoiu, deschisă contribuțiilor tale.','An initiative by George Dobritoiu, open to your contributions.')}</p></div>
 <figure class="blueprint-figure"><div class="blueprint-label"><span>PROIECT ROMÂNIA</span><span aria-hidden="true">01 / RO</span></div><img src="/assets/img/proiect-romania-logo-tricolor.png" width="1536" height="1024" alt="{t('Harta României, jumătate siluetă și jumătate schiță de arhitect','Romania’s map, half solid silhouette and half architectural sketch')}" fetchpriority="high" decoding="async"/><figcaption><strong>{t('Viitorul începe cu o schiță.','The future starts with a sketch.')}</strong><span>{t('Îl construim prin idei bine gândite și pași concreți.','We build it through thoughtful ideas and practical steps.')}</span></figcaption></figure>
</section>
<section class="home-mission"><div class="wrap mission-inner"><div><p class="eyebrow">{t('DE CE EXISTĂ PROIECT ROMÂNIA','WHY PROIECT ROMÂNIA EXISTS')}</p><h2>{t('De la „ar trebui”<br>la „iată cum”.','From “we should”<br>to “here is how”.')}</h2></div><div><p>{t('O idee devine utilă când poate fi înțeleasă, discutată și pusă în practică. Aici găsești proiecte cu autori identificați, soluții explicate și pași de urmat — de la sport și educație la solidaritate și organizare civică.','An idea becomes useful when people can understand it, discuss it and put it into practice. Find projects with named authors, explained solutions and practical next steps — from sport and education to solidarity and civic organisation.')}</p><a class="home-text-link" href="{about}">{t('Despre platformă și principiile noastre','About the platform and our principles')} →</a></div></div></section>
<section class="wrap home-showcase" id="proiecte-selectate" aria-labelledby="showcase-title"><div class="home-section-heading"><div><p class="eyebrow">{t('IDEI CARE PRIND CONTUR','IDEAS TAKING SHAPE')}</p><h2 id="showcase-title">{t('Descoperă ce putem construi.','Discover what we can build.')}</h2></div><a class="home-text-link" href="{directory}">{t('Toate cele','All')} {len(items)} {t('proiecte și inițiative','projects and initiatives')} →</a></div>
<article class="home-feature"><div class="home-feature-photo"><img src="/assets/img/football-960.webp" srcset="/assets/img/football-480.webp 480w, /assets/img/football-960.webp 960w, /assets/img/football-1600.webp 1600w" sizes="(max-width:760px) 100vw, 50vw" width="1600" height="1200" alt="{t('Teren de fotbal pe iarbă','A grass football pitch')}" loading="lazy"/><span>{t('SPORT · PROPUNERE PENTRU DEZBATERE','SPORT · PROPOSAL FOR DISCUSSION')}</span></div><div class="home-feature-copy"><img class="home-feature-logo" src="/assets/img/fotbal-pentru-viitor-logo.png" width="150" height="80" alt="Fotbal pentru Viitor" loading="lazy"/><h3><a href="{football}">{t('Generațiile de aur se formează.','Great generations are developed.')}</a></h3><p>{t('Fotbal pentru Viitor propune o reconstrucție de la bază: acces pentru copii, antrenori pregătiți, cluburi bine organizate și comunități implicate. Explorează planul și documentația.','Football for the Future proposes rebuilding from the grassroots: access for children, trained coaches, well-run clubs and involved communities. Explore the plan and its documentation.')}</p><p class="meta">George Dobritoiu · {t('Orizont','Horizon')} 2030–2040</p><a class="home-text-link" href="{football}">{t('Explorează Fotbal pentru Viitor','Explore Football for the Future')} →</a></div></article>
<div class="directory-grid editorial-project-grid">{featured}</div><p class="home-editorial-note">{t('Propuneri, ghiduri și inițiative independente. Fiecare își păstrează autorul și identitatea; publicarea nu înseamnă că implementarea sau finanțarea sunt asigurate.','Proposals, guides and independent initiatives. Each retains its author and identity; publication does not mean implementation or funding is secured.')}</p>
<div class="home-domains"><h3>{t('Ce domeniu te interesează?','What matters to you?')}</h3><nav aria-label="{t('Domenii de proiecte','Project categories')}">{categories}</nav></div></section>
<section class="home-method"><div class="wrap"><div class="home-section-heading"><div><p class="eyebrow">{t('CUM LUCRĂM','HOW WE WORK')}</p><h2>{t('Idei argumentate.<br>Pași de urmat.','Ideas with evidence.<br>Practical next steps.')}</h2></div><a class="home-text-link" href="{how}">{t('Cum funcționează platforma','How the platform works')} →</a></div><ol class="home-steps">{steps_html}</ol></div></section>
<section class="wrap home-participate"><div><p class="eyebrow">{t('LOCUL TĂU ÎN PROIECT','YOUR PART IN THE PROJECT')}</p><h2>{t('Experiența ta poate<br>face diferența.','Your experience can<br>make a difference.')}</h2><p>{t('Poți veni cu o idee, poți îmbunătăți un proiect sau poți ajuta o comunitate să facă primul pas.','Bring an idea, improve a project or help a community take its first step.')}</p></div><div class="participation-options"><a href="{propose}"><div><strong>{t('Am o idee de proiect','I have a project idea')}</strong><span>{t('Vezi ce trebuie să conțină o propunere.','See what a proposal should include.')}</span></div><span aria-hidden="true">↗</span></a><a href="{contact}"><div><strong>{t('Vreau să contribui','I want to contribute')}</strong><span>{t('Cu experiență, feedback sau sprijin local.','With expertise, feedback or local support.')}</span></div><span aria-hidden="true">↗</span></a><a href="/oportunitati-de-finantare"><div><strong>{t('Caut resurse pentru o inițiativă','I am looking for resources')}</strong><span>{t('Explorează informațiile despre finanțare.','Explore funding information (in Romanian).')}</span></div><span aria-hidden="true">↗</span></a></div></section>
'''
