from pathlib import Path
from bs4 import BeautifulSoup
import html,json
P=Path(__file__).resolve().parents[2]
path='/proiecte/hopefriday'
s=BeautifulSoup((P/'initiative-cetatenesti/oradea-refoloseste.html').read_text(),'html.parser')
title='HopeFriday — companiile susțin comunitățile'
desc='Relansarea inițiativei lui George Dobritoiu: sponsorizări transparente pentru asociații și fundații, cu reguli fiscale actualizate.'
for t in s.select('title'):t.string=title+' | Proiect România'
for t in s.select('meta[name="description"],meta[property="og:description"]'):t['content']=desc
s.select_one('meta[property="og:title"]')['content']=title
s.select_one('meta[property="og:url"]')['content']='https://proiectromania.ro'+path
s.select_one('link[rel="canonical"]')['href']='https://proiectromania.ro'+path
body='''<article class="funding-article wrap"><a href="/proiecte">← Proiecte</a><p class="eyebrow">SOLIDARITATE · GEORGE DOBRITOIU</p><h1>HopeFriday</h1><p class="lead">O parte din impozitul companiilor poate deveni sprijin pentru comunități.</p><p class="meta">Publicat la 10 octombrie 2026 · Ghid fiscal verificat la aceeași dată</p><aside class="funding-deadline"><strong>Relansare în pregătire.</strong> Publicăm propunerea și căutăm colaboratori. Participanții istorici nu sunt prezentați ca parteneri ai relansării.</aside><div class="funding-body">
<h2>Despre inițiativă</h2><p>HopeFriday este o inițiativă a lui George Dobritoiu, începută în 2015 și prezentată în cadrul Proiect România. Invităm companiile să susțină asociații și fundații prin sponsorizări transparente, folosind mecanismele fiscale aplicabile.</p><h2>Beneficiari și donatori</h2><p>Lista de mai jos cuprinde participări documentate la edițiile anterioare. Participarea la noua ediție se confirmă separat; lista se actualizează pe baza acordului și a documentelor fiecărei organizații.</p><h3>Beneficiar documentat</h3><ul><li><strong>Autism Voice / ATCA</strong> — sprijin pentru activități destinate copiilor cu autism. Organizația documentează o sponsorizare de 2.000 lei din partea Evo Horeca în 2016.</li></ul><h3>Donatori documentați</h3><p>Sursa beneficiarului confirmă participarea și donații cumulate de peste 20.000 lei în ediția 2015 pentru următoarele companii:</p><ul><li>Global Network — Drimus.ro și Ergos.ro;</li><li>Evo Horeca — EvoHoreca.ro;</li><li>Xact Consulting — ScauneOnline.ro;</li><li>Arbex Art Decor — Deco-Perete.ro și Arta-Inramarii.ro.</li></ul><p>Sumele individuale din 2015 nu sunt precizate în sursă. Evo Horeca este menționată distinct cu sponsorizarea de 2.000 lei din 2016.</p><p><a href="https://autismvoice.ro/atca-participa-la-hopefriday-2016-ca-sa-facem-lucruri-frumoase-cu-broscuta-norocoasa/">Sursa listei: Autism Voice</a></p>
<h2>Cum funcționează HopeFriday</h2><p>O campanie care conectează companii cu asociații și fundații, explică pașii sponsorizării și urmărește rezultatele. HopeFriday poate avea o zi anuală de mobilizare, susținută de informare pe tot parcursul anului. Data noii ediții va fi anunțată după organizarea pilotului.</p><p>Modelul propus păstrează transferurile direct între companie și organizația beneficiară sau prin ANAF, după mecanismul ales. Această pagină este de informare și colaborare; nu colectează bani.</p>
<h2>Regulile fiscale pe care le folosim acum</h2><p>Pentru o companie plătitoare de impozit pe profit, plafonul general al creditului fiscal este valoarea cea mai mică dintre <strong>0,75% din cifra de afaceri</strong> și <strong>20% din impozitul pe profit datorat</strong>. Vorbim despre impozit, nu despre 20% din profit. Cheltuiala de sponsorizare este nedeductibilă la calculul rezultatului fiscal; scăderea se face din impozit, în condițiile legii.</p><p>Microîntreprinderile pot sponsoriza, dar facilitatea de scădere din impozitul pe veniturile microîntreprinderilor a fost eliminată de la 1 ianuarie 2024. Regula istorică de 0,5% din cifra de afaceri se înlocuiește, în acest ghid, cu plafonul general actual de 0,75%.</p>
<h3>1. Sponsorizare directă</h3><p>Compania încheie un contract scris și transferă sprijinul beneficiarului. Pentru facilitatea fiscală acordată sponsorizării unui ONG, se verifică înscrierea acestuia în registrul ANAF la data contractului. Contabilul stabilește suma eligibilă și declarațiile necesare.</p>
<h3>2. Redirecționare prin formularul 177</h3><p>Partea disponibilă din plafon poate fi solicitată prin formularul 177, până la termenul legal al declarației anuale de impozit pe profit pentru anul respectiv. ANAF efectuează plata; ONG-ul trebuie să figureze în registru la data plății. Sumele deja utilizate și reportările aplicabile intră în calcul, pentru a evita dublarea.</p><p>Termenul de 25 iunie 2026 pentru anul fiscal 2025 a trecut. Calendarul pentru anul fiscal 2026 se verifică separat, potrivit regimului companiei și legislației aplicabile; nu extrapolăm automat termenul din 2025.</p><p>Contribuabilii care datorează impozit pe profit la nivelul impozitului minim pe cifra de afaceri nu pot folosi redirecționarea prin formularul 177, potrivit procedurii ANAF. Grupurile fiscale și celelalte regimuri speciale se analizează separat.</p>
<h3>Exemplu orientativ</h3><p>La o cifră de afaceri de 1.000.000 lei și un impozit pe profit de 40.000 lei, limitele sunt 7.500 lei și 8.000 lei. Plafonul general este 7.500 lei, înainte de scăderea sumelor deja utilizate sau a reportărilor aplicabile. Calculul final aparține contabilului companiei.</p>
<h2>Cum poate participa o companie</h2><ol><li>Confirmă regimul fiscal și plafonul disponibil cu contabilul.</li><li>Alege o cauză și verifică organizația, registrul ANAF și contul bancar.</li><li>Stabilește sprijinul și încheie contractul de sponsorizare.</li><li>Realizează transferul direct sau depune formularul 177, după caz.</li><li>Păstrează documentele și solicită un raport al folosirii sprijinului.</li></ol>
<h2>Ce cerem organizațiilor interesate</h2><p>O prezentare cu problema, beneficiarii, activitățile, bugetul, responsabilul și rezultatele urmărite; datele juridice și financiare verificabile; declarația conflictelor de interese și un angajament de raportare. Publicarea unei organizații în viitorul catalog va fi însoțită de data verificării. Comunicarea sponsorizării respectă limitele legale și protejează datele beneficiarilor.</p>
<h2>Un pilot mic, cu rezultate publice</h2><p>Propunem, ca țintă de lucru, 5–10 companii și 3–5 organizații. Începem cu o etapă de pregătire de 30 de zile, apoi urmărim separat contractele, cererile depuse și banii efectiv primiți. Țintele și calendarul se confirmă după recrutarea participanților.</p><p>Resursele necesare sunt un coordonator, un contabil sau consultant fiscal, verificare juridică, verificarea organizațiilor și suport editorial. Bugetul operațional se publică înainte de lansarea campaniei, după estimarea contribuțiilor voluntare și a serviciilor necesare. Sprijinul pentru organizații rămâne separat de cheltuielile de organizare.</p><p>Indicatorii pilotului: companii participante, organizații verificate, sponsorizări încasate, cereri 177 aprobate și rezultate raportate de beneficiari. Riscurile urmărite: eligibilitate fiscală greșită, depășirea plafonului, întârzierea plăților și raportare insuficientă.</p>
<h2>Căutăm colaboratori</h2><p>Companii, asociații, fundații, contabili și specialiști juridici care vor să contribuie la relansare pot scrie la <a href="mailto:salut@proiectromania.ro?subject=HopeFriday%20%E2%80%94%20colaborare">salut@proiectromania.ro</a>. Menționează rolul în care vrei să participi și ce poți aduce pilotului.</p>
<h2>Surse și actualizare</h2><ul><li><a href="https://static.anaf.ro/static/10/Cluj/cj_sponsorizari_19aug2025.pdf">ANAF: regimul sponsorizării și procedura de redirecționare</a> — Codul fiscal, art. 25 și 42; Legea nr. 32/1994; OPANAF nr. 3562/2024.</li><li><a href="https://static.anaf.ro/static/10/Brasov/Brasov/micro_01012024.pdf">ANAF: eliminarea facilității pentru microîntreprinderi din 2024</a>.</li><li><a href="https://static.anaf.ro/static/3/Cluj/20260615103333_informatii%20de%20interes%20public%20.pdf">ANAF: termenul formularului 177 pentru anul fiscal 2025</a>.</li><li><a href="https://static.anaf.ro/static/10/Anaf/Declaratii_R/177.html">ANAF: formularul 177 și instrucțiunile actualizate</a>.</li></ul><p>Ghid general, verificat la 10 octombrie 2026. Deciziile și calculul fiscal se verifică pentru situația concretă a companiei. Pagina va fi revizuită înainte de lansarea pilotului și la modificarea regulilor.</p></div><div class="funding-share"><button class="btn share" data-title="HopeFriday" data-text="Companiile susțin comunitățile. Descoperă propunerea de relansare HopeFriday.">Distribuie proiectul ↗</button></div></article>'''
s.select_one('main').clear();s.select_one('main').append(BeautifulSoup(body,'html.parser'))
(P/'proiecte/hopefriday.html').write_text(str(s))
card=BeautifulSoup('<article class="project-card" id="hopefriday-card"><div class="project-card-body"><p class="eyebrow">SOLIDARITATE · RELANSARE ÎN PREGĂTIRE</p><h2><a href="/proiecte/hopefriday">HopeFriday</a></h2><p>Companiile susțin asociații și fundații prin sponsorizări transparente. O inițiativă începută în 2015, în cadrul Proiect România.</p><p class="meta">George Dobritoiu · Ghid fiscal actualizat</p><a class="btn" href="/proiecte/hopefriday">Descoperă proiectul ↗</a></div></article>','html.parser')
for f in ['proiecte.html','index.html']:
 d=BeautifulSoup((P/f).read_text(),'html.parser')
 if d.select_one('#hopefriday-card'):
  d.select_one('#hopefriday-card').replace_with(BeautifulSoup(str(card),'html.parser'))
 else:
  old=d.select_one('.project-card');old.insert_after(BeautifulSoup(str(card),'html.parser'))
 if f=='proiecte.html':
  m=d.select_one('main section.section-space > .meta')
  if m:m.string='2 proiecte · Sport și solidaritate · Propuneri pentru dezbatere'
 (P/f).write_text(str(d))
v=json.loads((P/'vercel.json').read_text())
if not any(x['source']==path for x in v['rewrites']):v['rewrites'].append({'source':path,'destination':path+'.html'})
if not any(x['source']==path+'.html' for x in v['redirects']):v['redirects'].append({'source':path+'.html','destination':path,'statusCode':301})
(P/'vercel.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
sm=(P/'sitemap.xml').read_text()
if path+'</loc>' not in sm:sm=sm.replace('</urlset>','<url><loc>https://proiectromania.ro'+path+'</loc><lastmod>2026-10-10</lastmod></url></urlset>')
(P/'sitemap.xml').write_text(sm)
print('Built HopeFriday project and RO listings')
